### PR TITLE
Bugfix/114 deploy to releases bucket from natcap's fork

### LINKED ISSUE #114: artifacts are not deploying to our releases bucket
When builds happen on natcap's fork of the repo (e.g. on a PR's merge commit) artifacts should deploy to releases.naturalcapitalproject.org

That's not working, I think because we're referencing `github.actor` when we want `github.repository_owner`

When builds happen on our personal forks, they should upload to natcap-dev-build-artifacts bucket. And that does seem to be working, so long as you add the GCP secret to your github account.

### PR DESCRIPTION
**Pull request by davemfish**
Fixes #114 - hopefully. The deploy step is purposefully skipped during pull requests, so I'm not sure how we can test that step, on natcap's fork, except by clicking "merge". Any ideas?

### CODE REVIEW

**Comment by phargogh** [comment]
Since this has to do with some repo-specific configuration, what about configuring branch protection rules to allow this branch, pushing your branch to this repo?  When it's all good to go, we can PR the branch (within this repo) into `main` and then clean things up as needed.

It's times like this where I wish github actions had a simulator.

**Comment by davemfish** [comment]
Okay, I tested this by running on a branch in natcap's repo and we got a successful deployment to our bucket: http://releases.naturalcapitalproject.org/

Thanks for all the suggestions!

**Comment by davemfish** [comment]
I'll delete that natcap-owned branch when we merge this. All the changes I made there I also pushed to my davemfish branch, which is the source branch here.

**Review by phargogh — APPROVED** [review]
Makes sense to me!

**Comment by phargogh** [comment]
One puppeteer test is failing, but that shouldn't have anything to do with the github actions syntax touched by the PR.  Merging!

**Pull request merged**
